// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Project.Data;

#nullable disable

namespace Cabrynt.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916163102_AddRideQuoteSnapshots")]
    partial class AddRideQuoteSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Project.Models.Maintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("NextInspectionMileage")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ServiceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TechnicianName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("Maintenances", t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_Cost", "\"Cost\" >= 0");

                            t.HasCheckConstraint("CK_Maintenance_NextInspectionMileage", "\"NextInspectionMileage\" > 0");

                            t.HasCheckConstraint("CK_Maintenance_ServiceDate", "\"ServiceDate\" <= CURRENT_DATE");
                        });
                });

            modelBuilder.Entity("Project.Models.PassengerProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("HomeAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<int>("Points")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredPaymentMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("UserId");

                    b.ToTable("PassengerProfiles", t =>
                        {
                            t.HasCheckConstraint("CK_Passenger_Points", "\"Points\" >= 0");
                        });
                });

            modelBuilder.Entity("Project.Models.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("DepartureLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DepartureLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("DepartureLongitude")
                        .HasColumnType("double precision");

                    b.Property<double>("DestinationLatitude")
                        .HasColumnType("double precision");

                    b.Property<string>("DestinationLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("DestinationLongitude")
                        .HasColumnType("double precision");

                    b.Property<decimal>("Distance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Duration")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("EstimatedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("EstimatedTripDuration")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int?>("EstimatedTripDurationSource")
                        .HasColumnType("integer");

                    b.Property<int>("PassengerProfileUserId")
                        .HasColumnType("integer");

                    b.Property<int>("PreferredVehicleType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RideStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TripDurationModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("PassengerProfileUserId");

                    b.ToTable("Rides", t =>
                        {
                            t.HasCheckConstraint("CK_Ride_Distance", "\"Distance\" >= 0");

                            t.HasCheckConstraint("CK_Ride_Duration", "\"Duration\" >= 0");

                            t.HasCheckConstraint("CK_Ride_EstimatedPrice", "\"EstimatedPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("Project.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PassengerProfileUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReportTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("TicketPriority")
                        .HasColumnType("integer");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PassengerProfileUserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AccountCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LicencePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<int>("VehicleStatus")
                        .HasColumnType("integer");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LicencePlate")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles", t =>
                        {
                            t.HasCheckConstraint("CK_Vehicle_Year", "\"Year\" >= 1970 AND \"Year\" <= EXTRACT(YEAR FROM CURRENT_DATE)");
                        });
                });

            modelBuilder.Entity("Project.Models.Maintenance", b =>
                {
                    b.HasOne("Project.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Project.Models.PassengerProfile", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Project.Models.PassengerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.Ride", b =>
                {
                    b.HasOne("Project.Models.PassengerProfile", "PassengerProfile")
                        .WithMany("Rides")
                        .HasForeignKey("PassengerProfileUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PassengerProfile");
                });

            modelBuilder.Entity("Project.Models.Ticket", b =>
                {
                    b.HasOne("Project.Models.PassengerProfile", "PassengerProfile")
                        .WithMany("Tickets")
                        .HasForeignKey("PassengerProfileUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PassengerProfile");
                });

            modelBuilder.Entity("Project.Models.Vehicle", b =>
                {
                    b.HasOne("Project.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("Project.Models.Vehicle", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Project.Models.PassengerProfile", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
