name: cabrynt-trip-duration

services:
  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v6.0.0
    command: osrm-routed --algorithm mld /data/portugal-latest.osrm
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./data/osrm:/data:ro
